// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHzdKlIsvsEng7nPiwgX1sigKoBSx75E',
    appId: '1:132010785496:web:f0a0c6cc28a3e95175f5ad',
    messagingSenderId: '132010785496',
    projectId: 'pocketplanner-9b95f',
    authDomain: 'pocketplanner-9b95f.firebaseapp.com',
    storageBucket: 'pocketplanner-9b95f.appspot.com',
    measurementId: 'G-PH7JR18907',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeAjFF787Ub6Y7htxpklI2b3TReB6lyVg',
    appId: '1:132010785496:android:931f41eacf2104b875f5ad',
    messagingSenderId: '132010785496',
    projectId: 'pocketplanner-9b95f',
    storageBucket: 'pocketplanner-9b95f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLMsEVQocyncfjr_GvBFx8Ugir1ofvff4',
    appId: '1:132010785496:ios:920e3823edd50ad175f5ad',
    messagingSenderId: '132010785496',
    projectId: 'pocketplanner-9b95f',
    storageBucket: 'pocketplanner-9b95f.appspot.com',
    iosBundleId: 'com.example.pocketPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLMsEVQocyncfjr_GvBFx8Ugir1ofvff4',
    appId: '1:132010785496:ios:920e3823edd50ad175f5ad',
    messagingSenderId: '132010785496',
    projectId: 'pocketplanner-9b95f',
    storageBucket: 'pocketplanner-9b95f.appspot.com',
    iosBundleId: 'com.example.pocketPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHzdKlIsvsEng7nPiwgX1sigKoBSx75E',
    appId: '1:132010785496:web:a4fb9e76ee79809a75f5ad',
    messagingSenderId: '132010785496',
    projectId: 'pocketplanner-9b95f',
    authDomain: 'pocketplanner-9b95f.firebaseapp.com',
    storageBucket: 'pocketplanner-9b95f.appspot.com',
    measurementId: 'G-FKZFEVTFEL',
  );

}